### ISSUE TITLE
Questions for discussion after first meeting with Gen3

### ISSUE THREAD

**Issue by diatomsRcool** [RTIInternational/NHLBI-BDC-DMC-HM#13]
1. Should we add a consent code to a participant with a date? People will be updating their consents per study. Do we need to keep the consent history?
2. I would map Gen3.Study.study_registration to an attribute in BDCHM.ResearchStudy but there is not an appropriate attribute there now.
3. I would map Gen3.Subject.consent_codes to an attribute in BDCHM.Participant but there is not an appropriate attribute there.
4. How should we handle populations and subcohorts in demographics? They look to be more granular than ethnicity.

**Comment by diatomsRcool** [comment]
Group discussion:
1. We should add a new element to represent consent. We should enable the ability to track consent codes over time because this could come up.
2. This captured in the system slot for Identifier
3. Similar to answer to number 1. Will add consent code as attribute of Participant
4. This seems to be a feature that we need to capture in detail. Prob not a good idea to have a free text field. No one is very sure about an answer. Anne needs to ask Gen3 more about how these fields are used. Population probably should not be a subclass of ethnicity. Should be its own attribute.

**Comment by bfurner** [comment]
@diatomsRcool, items #1 and #3 are handled in the latest PR i just merged.  You should find the new Consent entity in the docs here: https://bfurner.github.io/bdchm/Consent/.  There are also multi-valued "consent" attributes added to Participant and ResearchStudy
