### ISSUE TITLE
Questions for discussion after second meeting with Gen3

### ISSUE THREAD

**Issue by diatomsRcool** [RTIInternational/NHLBI-BDC-DMC-HM#15]
1. Every property has a submitter_id that is the primary key in Gen3. Should this be mapped to id in BDCHM?
2. How do we manage "baseline" measurements and "age at index"?

**Comment by bfurner** [comment]
1. `submitter_id` in Gen3 is a business identifier and as such I would map that to `identifier` slots in our model
2. `TimePoint` allows for capture of a) specific datetimes, b) an reference to another index timepoint and offset from that index timepoint, and/or c) an arbitrary `event_type` which could be baseline.  It should be a flexible enough data structure to allow for capture of the cases you bring up, but we'll want to see when someone tries to transform data into this.
