### ISSUE TITLE
QuestionnaireResponse.age_at_response duplicates Visit.age_at_visit_start linked through QuestionnaireResponse.associated_visit

### ISSUE THREAD

**Issue by diatomsRcool** [RTIInternational/NHLBI-BDC-DMC-HM#22]
Does QuestionnaireResponse.age_at_response duplicate Visit.age_at_visit_start because these are linked through QuestionnaireResponse.associated_visit?

**Comment by bfurner** [comment]
Currently `QuestionnaireResponse.associated_visit` is an optional attribute to handle the potential use case of questionnaires administered outside of an obviously associated visit.  Also, it is conceivable that a visit spans numerous days (e.g. an inpatient stay) and that a questionnaire may be administered on one day of a multiple-day visit and one wants to be able to track on which particular day a response is given.  In either of these use cases, having the ability to provide an `QuestionnaireResponse.age_at_response` would be useful.
